name: imagenet-classes-in-fid
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python >= 3.6
  - pip
  - numpy>=1.20
  - click>=8.0
  - pillow=8.3.1
  - pytorch=1.8.0
  - torchvision=0.9.0
  - cudatoolkit=11.1
  - requests=2.26.0
  - tqdm=4.62.2
  - ninja=1.10.2
  - pip:
    - matplotlib
    - pyyaml
    - opencv-python
    - scipy
    - tensorboard